package mod.upcraftlp.worldlimiter;

import mod.upcraftlp.worldlimiter.init.WorldBorderEvents;
import mod.upcraftlp.worldlimiter.proxy.CommonProxy;
import net.minecraft.util.text.TextFormatting;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.Mod.Instance;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.event.FMLServerStartedEvent;
import net.minecraftforge.fml.relauncher.Side;

@Mod(name = Reference.MODNAME, version = Reference.VERSION, acceptedMinecraftVersions = Reference.MCVERSION, modid = Reference.MOD_ID, acceptableRemoteVersions = "*")
public class Main {

	@Instance
	public static Main instance;
	
	@SidedProxy(clientSide = Reference.CLIENTSIDE_PATH, serverSide = Reference.SERVERSIDE_PATH)
	public static CommonProxy proxy;
	
	@EventHandler
	public void preInit(FMLPreInitializationEvent event) {
		proxy.preInit(event);
		if(event.getSide() == Side.CLIENT) {
			ModMetadata data = event.getModMetadata();
			data.autogenerated = false;
			data.version = Reference.VERSION;
			data.modId = Reference.MOD_ID;
			data.authorList.add(Reference.AUTHOR);
			data.name = TextFormatting.AQUA + Reference.MODNAME;
			data.url = Reference.UPDATE_URL;
		}
		
	}
	
	@EventHandler
	public void init(FMLInitializationEvent event) {
		proxy.init(event);
	}
	
	@EventHandler
	public void postInit(FMLPostInitializationEvent event) {
		proxy.postInit(event);
	}
	
	@EventHandler
	public void serverStarted(FMLServerStartedEvent event) {
		WorldBorderEvents.worldBorder(event);
	}
}
