package mod.upcraftlp.worldlimiter;

import com.google.common.collect.Lists;
import net.minecraft.util.text.TextFormatting;
import net.minecraftforge.event.world.WorldEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.relauncher.Side;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

@Mod(name = Reference.MODNAME, version = Reference.VERSION, acceptedMinecraftVersions = Reference.MCVERSION, modid = Reference.MODID, acceptableRemoteVersions = "*", updateJSON = Reference.INTERNAL_UPDATE_URL, guiFactory = Reference.CONFIG_GUI_FACTORY)
public class Main {

	private static final Logger log = LogManager.getFormatterLogger(Reference.MODID);

	public static Logger getLogger() { return log; }

	@EventHandler
	public void preInit(FMLPreInitializationEvent event) {
        ModConfig.init(event);
		if(event.getSide() == Side.CLIENT) {
			ModMetadata data = event.getModMetadata();
			data.autogenerated = false;
			data.version = Reference.VERSION;
			data.modId = Reference.MODID;
			data.authorList = Lists.newArrayList(Reference.AUTHOR);
			data.name = TextFormatting.AQUA + Reference.MODNAME;
			data.url = Reference.UPDATE_URL;
		}
	}

	@EventHandler
    public void worldLoad(WorldEvent.Load event) {
	    ModConfig.isDirty = true;
    }
}
